### ISSUE TITLE
Windows报错，ConnectionError，软件直接闪退

### ISSUE THREAD

**Issue by MarvinECL** [zhimingshenjun/DD_Monitor#101]
报错：
************!!!UNCAUGHT EXCEPTION!!!*********************
Type: <class 'requests.exceptions.ConnectionError'>
Value: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /jiafangjun/DD_KaoRou2/blob/master/%E6%84%9F%E8%B0%A2%E7%9F%B3%E6%B2%B9%E7%8E%8B.csv (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017FF614B7C8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
Traceback:
  File "pay.py", line 30, in run
   File "site-packages\requests\api.py", line 76, in get
   File "site-packages\requests\api.py", line 61, in request
   File "site-packages\requests\sessions.py", line 530, in request
   File "site-packages\requests\sessions.py", line 643, in send
   File "site-packages\requests\adapters.py", line 516, in send
************************************************************

完整log文件：
2021-02-22 17:09:51,892 [MainThread  ] [INFO ]  系统信息: 

主机名:           MSI
OS 名称:          Microsoft Windows 10 家庭中文版
OS 版本:          10.0.18363 暂缺 Build 18363
OS 制造商:        Microsoft Corporation
OS 配置:          独立工作站
OS 构建类型:      Multiprocessor Free
注册的所有人:     Windows 用户
注册的组织:       
产品 ID:          00342-30262-00002-AAOEM
初始安装日期:     2019/10/17, 10:58:53
系统启动时间:     2021/2/22, 15:12:18
系统制造商:       Micro-Star International Co., Ltd.
系统型号:         GL63 8RE
系统类型:         x64-based PC
处理器:           安装了 1 个处理器。
                  [01]: Intel64 Family 6 Model 158 Stepping 10 GenuineIntel ~2200 Mhz
BIOS 版本:        American Megatrends Inc. E16P5IMS.10D, 2018/10/18
Windows 目录:     C:\WINDOWS
系统目录:         C:\WINDOWS\system32
启动设备:         \Device\HarddiskVolume1
系统区域设置:     zh-cn;中文(中国)
输入法区域设置:   zh-cn;中文(中国)
时区:             (UTC+08:00) 北京，重庆，香港特别行政区，乌鲁木齐
物理内存总量:     16,231 MB
可用的物理内存:   10,617 MB
虚拟内存: 最大值: 18,279 MB
虚拟内存: 可用:   9,363 MB
虚拟内存: 使用中: 8,916 MB
页面文件位置:     C:\pagefile.sys
域:               WORKGROUP
登录服务器:       \\MSI
修补程序:         安装了 27 个修补程序。
                  [01]: KB4601556
                  [02]: KB4497165
                  [03]: KB4513661
                  [04]: KB4515383
                  [05]: KB4516115
                  [06]: KB4517245
                  [07]: KB4521863
                  [08]: KB4524244
                  [09]: KB4524569
                  [10]: KB4525419
                  [11]: KB4528759
                  [12]: KB4535680
                  [13]: KB4537759
                  [14]: KB4538674
                  [15]: KB4541338
                  [16]: KB4552152
                  [17]: KB4561600
                  [18]: KB4565554
                  [19]: KB4569073
                  [20]: KB4576751
                  [21]: KB4577586
                  [22]: KB4577670
                  [23]: KB4580325
                  [24]: KB4586863
                  [25]: KB4598479
                  [26]: KB4601395
                  [27]: KB5001028
网卡:             安装了 4 个 NIC。
                  [01]: Intel(R) Wireless-AC 9462
                      连接名:      WLAN 2
                      启用 DHCP:   是
                      DHCP 服务器: 192.168.3.1
                      IP 地址
                        [01]: 192.168.3.4
                        [02]: fe80::a583:5c39:add9:d6c8
                  [02]: Qualcomm Atheros AR8171/8175 PCI-E Gigabit Ethernet Controller (NDIS 6.30)
                      连接名:      以太网 2
                      状态:        媒体连接已中断
                  [03]: Bluetooth Device (Personal Area Network)
                      连接名:      蓝牙网络连接 3
                      状态:        媒体连接已中断
                  [04]: ASIX AX88772C USB2.0 to Fast Ethernet Adapter
                      连接名:      以太网 4
                      状态:        媒体连接已中断
Hyper-V 要求:     虚拟机监视器模式扩展: 是
                  固件中已启用虚拟化: 是
                  二级地址转换: 是
                  数据执行保护可用: 是

2021-02-22 17:09:51,892 [MainThread  ] [INFO ]  GPU信息: 
AdapterCompatibility=Intel Corporation
Caption=Intel(R) UHD Graphics 630
DeviceID=VideoController1
DriverDate=20180827000000.000000-000
DriverVersion=24.20.100.6292
VideoModeDescription=

AdapterCompatibility=NVIDIA
Caption=NVIDIA GeForce GTX 1060
DeviceID=VideoController2
DriverDate=20210122000000.000000-000
DriverVersion=27.21.14.6140
VideoModeDescription=1920 x 1080 x 4294967296 种颜色
2021-02-22 17:09:51,892 [MainThread  ] [INFO ]  libvlc env: PYTHON_VLC_LIB_PATH=
2021-02-22 17:09:51,892 [MainThread  ] [INFO ]  plugin env: PYTHON_VLC_MODULE_PATH=
2021-02-22 17:09:51,892 [MainThread  ] [INFO ]  libvlc path: F:\chrome downloads\DD监控室\libvlc.dll
2021-02-22 17:09:51,892 [MainThread  ] [INFO ]  vlc version: b'2.2.8 Weatherwax'
2021-02-22 17:09:52,204 [MainThread  ] [INFO ]  嵌入窗0 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-22 17:09:52,229 [MainThread  ] [INFO ]  悬浮窗9 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-22 17:09:52,239 [MainThread  ] [INFO ]  VLC设置完毕 1 / 9
2021-02-22 17:09:52,264 [MainThread  ] [INFO ]  嵌入窗1 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-22 17:09:52,284 [MainThread  ] [INFO ]  悬浮窗10 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-22 17:09:52,289 [MainThread  ] [INFO ]  VLC设置完毕 2 / 9
2021-02-22 17:09:52,309 [MainThread  ] [INFO ]  嵌入窗2 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-22 17:09:52,334 [MainThread  ] [INFO ]  悬浮窗11 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-22 17:09:52,339 [MainThread  ] [INFO ]  VLC设置完毕 3 / 9
2021-02-22 17:09:52,359 [MainThread  ] [INFO ]  嵌入窗3 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-22 17:09:52,384 [MainThread  ] [INFO ]  悬浮窗12 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-22 17:09:52,389 [MainThread  ] [INFO ]  VLC设置完毕 4 / 9
2021-02-22 17:09:52,409 [MainThread  ] [INFO ]  嵌入窗4 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-22 17:09:52,429 [MainThread  ] [INFO ]  悬浮窗13 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-22 17:09:52,434 [MainThread  ] [INFO ]  VLC设置完毕 5 / 9
2021-02-22 17:09:52,454 [MainThread  ] [INFO ]  嵌入窗5 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-22 17:09:52,479 [MainThread  ] [INFO ]  悬浮窗14 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-22 17:09:52,484 [MainThread  ] [INFO ]  VLC设置完毕 6 / 9
2021-02-22 17:09:52,504 [MainThread  ] [INFO ]  嵌入窗6 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-22 17:09:52,524 [MainThread  ] [INFO ]  悬浮窗15 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-22 17:09:52,529 [MainThread  ] [INFO ]  VLC设置完毕 7 / 9
2021-02-22 17:09:52,549 [MainThread  ] [INFO ]  嵌入窗7 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-22 17:09:52,574 [MainThread  ] [INFO ]  悬浮窗16 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-22 17:09:52,579 [MainThread  ] [INFO ]  VLC设置完毕 8 / 9
2021-02-22 17:09:52,599 [MainThread  ] [INFO ]  嵌入窗8 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-22 17:09:52,624 [MainThread  ] [INFO ]  悬浮窗17 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-22 17:09:52,624 [MainThread  ] [INFO ]  VLC设置完毕 9 / 9
2021-02-22 17:09:52,775 [MainThread  ] [INFO ]  UI构造完毕
2021-02-22 17:09:52,807 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 866, in mediaStop
TypeError: 'method' object is not connected
2021-02-22 17:09:52,809 [Dummy-1     ] [INFO ]  弹幕IP: 120.92.78.57
2021-02-22 17:09:52,866 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 866, in mediaStop
TypeError: 'method' object is not connected
2021-02-22 17:09:52,874 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 866, in mediaStop
TypeError: 'method' object is not connected
2021-02-22 17:09:52,904 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 866, in mediaStop
TypeError: 'method' object is not connected
2021-02-22 17:09:52,912 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 866, in mediaStop
TypeError: 'method' object is not connected
2021-02-22 17:09:52,940 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 866, in mediaStop
TypeError: 'method' object is not connected
2021-02-22 17:13:31,298 [MainThread  ] [INFO ]  roomID:22829409
2021-02-22 17:13:31,298 [MainThread  ] [INFO ]  
2021-02-22 17:13:31,298 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 767, in stopDanmuMessage
TypeError: 'method' object is not connected
2021-02-22 17:13:31,768 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 882, in setMedia
TypeError: 'method' object is not connected
2021-02-22 17:13:31,782 [Dummy-2     ] [INFO ]  尝试打开 22829409 的弹幕Socket
2021-02-22 17:13:33,806 [MainThread  ] [INFO ]  roomID:21292831
2021-02-22 17:13:33,806 [MainThread  ] [INFO ]  
2021-02-22 17:13:33,806 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 767, in stopDanmuMessage
TypeError: 'method' object is not connected
2021-02-22 17:13:34,283 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 882, in setMedia
TypeError: 'method' object is not connected
2021-02-22 17:13:34,291 [Dummy-3     ] [INFO ]  尝试打开 21292831 的弹幕Socket
2021-02-22 17:13:37,051 [MainThread  ] [INFO ]  roomID:5050
2021-02-22 17:13:37,051 [MainThread  ] [INFO ]  
2021-02-22 17:13:37,051 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 767, in stopDanmuMessage
TypeError: 'method' object is not connected
2021-02-22 17:13:37,559 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 882, in setMedia
TypeError: 'method' object is not connected
2021-02-22 17:13:37,566 [Dummy-4     ] [INFO ]  尝试打开 5050 的弹幕Socket
2021-02-22 17:13:42,569 [MainThread  ] [INFO ]  exchange:0:22829409
2021-02-22 17:13:42,569 [MainThread  ] [INFO ]  
2021-02-22 17:13:42,569 [MainThread  ] [INFO ]  0
2021-02-22 17:13:42,569 [MainThread  ] [INFO ]   
2021-02-22 17:13:42,569 [MainThread  ] [INFO ]  0
2021-02-22 17:13:42,569 [MainThread  ] [INFO ]  
2021-02-22 17:13:46,641 [MainThread  ] [INFO ]  exchange:1:5050
2021-02-22 17:13:46,641 [MainThread  ] [INFO ]  
2021-02-22 17:13:46,641 [MainThread  ] [INFO ]  1
2021-02-22 17:13:46,641 [MainThread  ] [INFO ]   
2021-02-22 17:13:46,641 [MainThread  ] [INFO ]  5
2021-02-22 17:13:46,641 [MainThread  ] [INFO ]  
2021-02-22 17:14:14,626 [Dummy-5     ] [ERROR]  
************!!!UNCAUGHT EXCEPTION!!!*********************
Type: <class 'requests.exceptions.ConnectionError'>
Value: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /jiafangjun/DD_KaoRou2/blob/master/%E6%84%9F%E8%B0%A2%E7%9F%B3%E6%B2%B9%E7%8E%8B.csv (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017FF614B7C8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
Traceback:
  File "pay.py", line 30, in run
   File "site-packages\requests\api.py", line 76, in get
   File "site-packages\requests\api.py", line 61, in request
   File "site-packages\requests\sessions.py", line 530, in request
   File "site-packages\requests\sessions.py", line 643, in send
   File "site-packages\requests\adapters.py", line 516, in send
************************************************************

**Comment by MarvinECL** [comment]
快速思考了一下，有可能是因为我开的代理。我是常驻UAC模式。等我把代理关了，软件重新下载一下，然后再试试

**Comment by ssysm** [comment]
获取不到预设vtb的文件 一般是个关于梯子的网络问题

**Comment by MarvinECL** [comment]
> 获取不到预设vtb的文件 一般是个关于梯子的网络问题

是的，今天把飞机关了，挂了一天，就没问题了
