### ISSUE TITLE
在使用悬浮窗模式时，弹幕机无法同时置顶。并且在此时关闭悬浮窗，软件会直接无相应，得手动杀掉进程。

### ISSUE THREAD

**Issue by iPixelOldC** [zhimingshenjun/DD_Monitor#72]
如题，系统是Manjaro Linux,桌面是KDE5。软件的版本是，刚刚直接git clone下来的最新版。
下面是日志。
> 2021-02-05 19:49:50,235 [MainThread  ] [INFO ]  系统信息: 
> 架构：                           x86_64
> CPU 运行模式：                   32-bit, 64-bit
> 字节序：                         Little Endian
> Address sizes:                   39 bits physical, 48 bits virtual
> CPU:                             4
> 在线 CPU 列表：                  0-3
> 每个核的线程数：                 2
> 每个座的核数：                   2
> 座：                             1
> NUMA 节点：                      1
> 厂商 ID：                        GenuineIntel
> CPU 系列：                       6
> 型号：                           61
> 型号名称：                       Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
> 步进：                           4
> CPU MHz：                        2944.748
> CPU 最大 MHz：                   3000.0000
> CPU 最小 MHz：                   500.0000
> BogoMIPS：                       4790.53
> 虚拟化：                         VT-x
> L1d 缓存：                       64 KiB
> L1i 缓存：                       64 KiB
> L2 缓存：                        512 KiB
> L3 缓存：                        4 MiB
> NUMA 节点0 CPU：                 0-3
> Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
> Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
> Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
> Vulnerability Meltdown:          Mitigation; PTI
> Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
> Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
> Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
> Vulnerability Srbds:             Mitigation; Microcode
> Vulnerability Tsx async abort:   Not affected
> 标记：                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap intel_pt xsaveopt dtherm ida arat pln pts md_clear flush_l1d
> 
> 2021-02-05 19:49:50,235 [MainThread  ] [INFO ]  GPU信息: 
> 00:00.0 Host bridge: Intel Corporation Broadwell-U Host Bridge -OPI (rev 09)
> 00:02.0 VGA compatible controller: Intel Corporation HD Graphics 5500 (rev 09)
> 00:03.0 Audio device: Intel Corporation Broadwell-U Audio Controller (rev 09)
> 00:14.0 USB controller: Intel Corporation Wildcat Point-LP USB xHCI Controller (rev 03)
> 00:16.0 Communication controller: Intel Corporation Wildcat Point-LP MEI Controller #1 (rev 03)
> 00:1b.0 Audio device: Intel Corporation Wildcat Point-LP High Definition Audio Controller (rev 03)
> 00:1c.0 PCI bridge: Intel Corporation Wildcat Point-LP PCI Express Root Port #1 (rev e3)
> 00:1c.3 PCI bridge: Intel Corporation Wildcat Point-LP PCI Express Root Port #4 (rev e3)
> 00:1c.4 PCI bridge: Intel Corporation Wildcat Point-LP PCI Express Root Port #5 (rev e3)
> 00:1d.0 USB controller: Intel Corporation Wildcat Point-LP USB EHCI Controller (rev 03)
> 00:1f.0 ISA bridge: Intel Corporation Wildcat Point-LP LPC Controller (rev 03)
> 00:1f.2 SATA controller: Intel Corporation Wildcat Point-LP SATA Controller [AHCI Mode] (rev 03)
> 00:1f.3 SMBus: Intel Corporation Wildcat Point-LP SMBus Controller (rev 03)
> 07:00.0 Network controller: Intel Corporation Wi-Fi 6 AX200 (rev 1a)
> 08:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Opal XT [Radeon R7 M265/M365X/M465]
> 
> 2021-02-05 19:49:50,236 [MainThread  ] [INFO ]  libvlc env: PYTHON_VLC_LIB_PATH=
> 2021-02-05 19:49:50,236 [MainThread  ] [INFO ]  plugin env: PYTHON_VLC_MODULE_PATH=
> 2021-02-05 19:49:50,236 [MainThread  ] [INFO ]  libvlc path: libvlc.so.5
> 2021-02-05 19:49:50,236 [MainThread  ] [INFO ]  vlc version: b'3.0.11.1 Vetinari'
> qt.qpa.xcb: QXcbConnection: XCB error: 5 (BadAtom), sequence: 462, resource id: 0, major code: 20 (GetProperty), minor code: 0
> 2021-02-05 19:49:51,029 [MainThread  ] [INFO ]  嵌入窗0 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
> 2021-02-05 19:49:51,082 [MainThread  ] [INFO ]  悬浮窗9 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
> 2021-02-05 19:49:51,135 [MainThread  ] [INFO ]  VLC设置完毕 1 / 9
> 2021-02-05 19:49:51,183 [MainThread  ] [INFO ]  嵌入窗1 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
> 2021-02-05 19:49:51,235 [MainThread  ] [INFO ]  悬浮窗10 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
> 2021-02-05 19:49:51,270 [MainThread  ] [INFO ]  VLC设置完毕 2 / 9
> 2021-02-05 19:49:51,329 [MainThread  ] [INFO ]  嵌入窗2 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
> 2021-02-05 19:49:51,382 [MainThread  ] [INFO ]  悬浮窗11 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
> 2021-02-05 19:49:51,423 [MainThread  ] [INFO ]  VLC设置完毕 3 / 9
> 2021-02-05 19:49:51,498 [MainThread  ] [INFO ]  嵌入窗3 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
> 2021-02-05 19:49:51,547 [MainThread  ] [INFO ]  悬浮窗12 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
> 2021-02-05 19:49:51,580 [MainThread  ] [INFO ]  VLC设置完毕 4 / 9
> 2021-02-05 19:49:51,631 [MainThread  ] [INFO ]  嵌入窗4 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
> 2021-02-05 19:49:51,687 [MainThread  ] [INFO ]  悬浮窗13 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
> 2021-02-05 19:49:51,720 [MainThread  ] [INFO ]  VLC设置完毕 5 / 9
> 2021-02-05 19:49:51,773 [MainThread  ] [INFO ]  嵌入窗5 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
> 2021-02-05 19:49:51,847 [MainThread  ] [INFO ]  悬浮窗14 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
> 2021-02-05 19:49:51,879 [MainThread  ] [INFO ]  VLC设置完毕 6 / 9
> 2021-02-05 19:49:51,931 [MainThread  ] [INFO ]  嵌入窗6 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
> 2021-02-05 19:49:51,988 [MainThread  ] [INFO ]  悬浮窗15 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
> 2021-02-05 19:49:52,024 [MainThread  ] [INFO ]  VLC设置完毕 7 / 9
> 2021-02-05 19:49:52,075 [MainThread  ] [INFO ]  嵌入窗7 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
> 2021-02-05 19:49:52,131 [MainThread  ] [INFO ]  悬浮窗16 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
> 2021-02-05 19:49:52,166 [MainThread  ] [INFO ]  VLC设置完毕 8 / 9
> 2021-02-05 19:49:52,220 [MainThread  ] [INFO ]  嵌入窗8 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
> 2021-02-05 19:49:52,277 [MainThread  ] [INFO ]  悬浮窗17 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
> 2021-02-05 19:49:52,314 [MainThread  ] [INFO ]  VLC设置完毕 9 / 9
> 2021-02-05 19:49:52,665 [MainThread  ] [INFO ]  UI构造完毕
> 2021-02-05 19:49:52,768 [Dummy-1     ] [INFO ]  弹幕IP: 198.18.2.205
> 2021-02-05 19:49:52,906 [MainThread  ] [ERROR]  停止弹幕出错
> Traceback (most recent call last):
>   File "/home/oldc/rust-projects/DD_Monitor/VideoWidget_vlc.py", line 866, in mediaStop
>     self.danmu.message.disconnect(self.playDanmu)
> TypeError: 'method' object is not connected
> 2021-02-05 19:49:53,258 [MainThread  ] [ERROR]  停止弹幕出错
> Traceback (most recent call last):
>   File "/home/oldc/rust-projects/DD_Monitor/VideoWidget_vlc.py", line 866, in mediaStop
>     self.danmu.message.disconnect(self.playDanmu)
> TypeError: 'method' object is not connected
> 2021-02-05 19:49:53,387 [MainThread  ] [ERROR]  停止弹幕出错
> Traceback (most recent call last):
>   File "/home/oldc/rust-projects/DD_Monitor/VideoWidget_vlc.py", line 866, in mediaStop
>     self.danmu.message.disconnect(self.playDanmu)
> TypeError: 'method' object is not connected
> 2021-02-05 19:49:53,461 [MainThread  ] [ERROR]  停止弹幕出错
> Traceback (most recent call last):
>   File "/home/oldc/rust-projects/DD_Monitor/VideoWidget_vlc.py", line 866, in mediaStop
>     self.danmu.message.disconnect(self.playDanmu)
> TypeError: 'method' object is not connected
> 2021-02-05 20:22:42,077 [MainThread  ] [ERROR]  停止弹幕出错
> Traceback (most recent call last):
>   File "/home/oldc/rust-projects/DD_Monitor/VideoWidget_vlc.py", line 866, in mediaStop
>     self.danmu.message.disconnect(self.playDanmu)
> TypeError: 'method' object is not connected
> 2021-02-05 20:22:42,087 [MainThread  ] [ERROR]  停止弹幕出错
> Traceback (most recent call last):
>   File "/home/oldc/rust-projects/DD_Monitor/VideoWidget_vlc.py", line 866, in mediaStop
>     self.danmu.message.disconnect(self.playDanmu)
> TypeError: 'method' object is not connected
> 2021-02-05 20:22:42,094 [MainThread  ] [ERROR]  停止弹幕出错
> Traceback (most recent call last):
>   File "/home/oldc/rust-projects/DD_Monitor/VideoWidget_vlc.py", line 866, in mediaStop
>     self.danmu.message.disconnect(self.playDanmu)
> TypeError: 'method' object is not connected
> 2021-02-05 20:22:42,100 [MainThread  ] [ERROR]  停止弹幕出错
> Traceback (most recent call last):
>   File "/home/oldc/rust-projects/DD_Monitor/VideoWidget_vlc.py", line 866, in mediaStop
>     self.danmu.message.disconnect(self.playDanmu)
> TypeError: 'method' object is not connected
> 2021-02-05 20:22:50,339 [MainThread  ] [ERROR]  停止弹幕出错
> Traceback (most recent call last):
>   File "/home/oldc/rust-projects/DD_Monitor/VideoWidget_vlc.py", line 866, in mediaStop
>     self.danmu.message.disconnect(self.playDanmu)
> TypeError: 'method' object is not connected
> 2021-02-05 20:22:50,347 [MainThread  ] [ERROR]  停止弹幕出错
> Traceback (most recent call last):
>   File "/home/oldc/rust-projects/DD_Monitor/VideoWidget_vlc.py", line 866, in mediaStop
>     self.danmu.message.disconnect(self.playDanmu)
> TypeError: 'method' object is not connected
> 2021-02-05 20:22:50,355 [MainThread  ] [ERROR]  停止弹幕出错
> Traceback (most recent call last):
>   File "/home/oldc/rust-projects/DD_Monitor/VideoWidget_vlc.py", line 866, in mediaStop
>     self.danmu.message.disconnect(self.playDanmu)
> TypeError: 'method' object is not connected
> 2021-02-05 20:22:50,363 [MainThread  ] [ERROR]  停止弹幕出错
> Traceback (most recent call last):
>   File "/home/oldc/rust-projects/DD_Monitor/VideoWidget_vlc.py", line 866, in mediaStop
>     self.danmu.message.disconnect(self.playDanmu)
> TypeError: 'method' object is not connected
> 2021-02-05 20:23:00,906 [MainThread  ] [INFO ]  exchange:1:0
> 2021-02-05 20:23:00,906 [MainThread  ] [INFO ]  
> 2021-02-05 20:23:00,906 [MainThread  ] [INFO ]  1
> 2021-02-05 20:23:00,907 [MainThread  ] [INFO ]   
> 2021-02-05 20:23:00,907 [MainThread  ] [INFO ]  1
> 2021-02-05 20:23:00,907 [MainThread  ] [INFO ]  
> qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 51002, resource id: 16424327, major code: 40 (TranslateCoords), minor code: 0
> 2021-02-05 20:23:43,738 [MainThread  ] [INFO ]  exchange:0:0
> 2021-02-05 20:23:43,738 [MainThread  ] [INFO ]  
> 2021-02-05 20:23:43,738 [MainThread  ] [INFO ]  0
> 2021-02-05 20:23:43,738 [MainThread  ] [INFO ]   
> 2021-02-05 20:23:43,738 [MainThread  ] [INFO ]  0
> 2021-02-05 20:23:43,738 [MainThread  ] [INFO ]  
> qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 7529, resource id: 16425660, major code: 40 (TranslateCoords), minor code: 0
> qt.qpa.xcb: QXcbConnection: XCB error: 5 (BadAtom), sequence: 509, resource id: 0, major code: 20 (GetProperty), minor code: 0
> 
> (firefox:256827): Gtk-WARNING **: 20:24:27.030: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
> 2021-02-05 20:25:07,534 [MainThread  ] [INFO ]  roomID:21396545
> 2021-02-05 20:25:07,535 [MainThread  ] [INFO ]  
> 2021-02-05 20:25:07,535 [MainThread  ] [ERROR]  停止弹幕出错
> Traceback (most recent call last):
>   File "/home/oldc/rust-projects/DD_Monitor/VideoWidget_vlc.py", line 767, in stopDanmuMessage
>     self.danmu.message.disconnect(self.playDanmu)
> TypeError: 'method' object is not connected
> 2021-02-05 20:25:08,227 [MainThread  ] [ERROR]  停止弹幕出错
> Traceback (most recent call last):
>   File "/home/oldc/rust-projects/DD_Monitor/VideoWidget_vlc.py", line 882, in setMedia
>     self.danmu.message.disconnect(self.playDanmu)
> TypeError: 'method' object is not connected
> 2021-02-05 20:25:08,237 [Dummy-2     ] [INFO ]  尝试打开 21396545 的弹幕Socket
> [00007f81e000f5d0] gl gl: Initialized libplacebo v2.72.0 (API v72)
> [00007f81a82fbae0] avcodec decoder: Using Intel iHD driver for Intel(R) Gen Graphics - 20.4.5 () for hardware decoding
> 2021-02-05 20:25:15,572 [MainThread  ] [INFO ]  exchange:0:21396545
> 2021-02-05 20:25:15,572 [MainThread  ] [INFO ]  
> 2021-02-05 20:25:15,572 [MainThread  ] [INFO ]  0
> 2021-02-05 20:25:15,573 [MainThread  ] [INFO ]   
> 2021-02-05 20:25:15,573 [MainThread  ] [INFO ]  0
> 2021-02-05 20:25:15,573 [MainThread  ] [INFO ]  
> 2021-02-05 20:29:22,696 [MainThread  ] [INFO ]  roomID:13355
> 2021-02-05 20:29:22,696 [MainThread  ] [INFO ]  
> 2021-02-05 20:29:22,697 [MainThread  ] [ERROR]  停止弹幕出错
> Traceback (most recent call last):
>   File "/home/oldc/rust-projects/DD_Monitor/VideoWidget_vlc.py", line 767, in stopDanmuMessage
>     self.danmu.message.disconnect(self.playDanmu)
> TypeError: 'method' object is not connected
> 2021-02-05 20:29:23,427 [MainThread  ] [ERROR]  停止弹幕出错
> Traceback (most recent call last):
>   File "/home/oldc/rust-projects/DD_Monitor/VideoWidget_vlc.py", line 882, in setMedia
>     self.danmu.message.disconnect(self.playDanmu)
> TypeError: 'method' object is not connected
> 2021-02-05 20:29:23,437 [Dummy-3     ] [INFO ]  尝试打开 13355 的弹幕Socket
> [NULL @ 0x7f8274109a00] Invalid NAL unit size (86529 > 64482).
> [NULL @ 0x7f8274109a00] missing picture in access unit with size 64633
> [h264 @ 0x7f8274109a00] Invalid NAL unit size (86529 > 64482).
> [h264 @ 0x7f8274109a00] Error splitting the input into NAL units.
> [00007f82ac007d60] gl gl: Initialized libplacebo v2.72.0 (API v72)
> [00007f82ac007d60] gl gl: Initialized libplacebo v2.72.0 (API v72)
> [00007f82ac007d60] gl gl: Initialized libplacebo v2.72.0 (API v72)
> 2021-02-05 20:29:40,097 [MainThread  ] [INFO ]  roomID:21547895
> 2021-02-05 20:29:40,097 [MainThread  ] [INFO ]  
> 2021-02-05 20:29:40,098 [MainThread  ] [ERROR]  停止弹幕出错
> Traceback (most recent call last):
>   File "/home/oldc/rust-projects/DD_Monitor/VideoWidget_vlc.py", line 767, in stopDanmuMessage
>     self.danmu.message.disconnect(self.playDanmu)
> TypeError: 'method' object is not connected
> 2021-02-05 20:29:40,615 [MainThread  ] [ERROR]  停止弹幕出错
> Traceback (most recent call last):
>   File "/home/oldc/rust-projects/DD_Monitor/VideoWidget_vlc.py", line 882, in setMedia
>     self.danmu.message.disconnect(self.playDanmu)
> TypeError: 'method' object is not connected
> 2021-02-05 20:29:40,628 [Dummy-4     ] [INFO ]  尝试打开 21547895 的弹幕Socket
> [h264 @ 0x7f81d414a340] Invalid NAL unit size (1321 > 685).
> [h264 @ 0x7f81d414a340] missing picture in access unit with size 689
> [00007f82100e7b60] gl gl: Initialized libplacebo v2.72.0 (API v72)
> [00007f81d40679c0] avcodec decoder: Using Intel iHD driver for Intel(R) Gen Graphics - 20.4.5 () for hardware decoding
> [h264 @ 0x7f81d40e4c80] Invalid NAL unit size (1321 > 685).
> [h264 @ 0x7f81d40e4c80] Error splitting the input into NAL units.
> [00007f82c4004360] gl gl: Initialized libplacebo v2.72.0 (API v72)
> [00007f82c4004360] gl gl: Initialized libplacebo v2.72.0 (API v72)
> [00007f82c4004360] gl gl: Initialized libplacebo v2.72.0 (API v72)
> 2021-02-05 20:38:59,600 [MainThread  ] [INFO ]  roomID:10209381
> 2021-02-05 20:38:59,600 [MainThread  ] [INFO ]  
> 2021-02-05 20:38:59,600 [MainThread  ] [ERROR]  停止弹幕出错
> Traceback (most recent call last):
>   File "/home/oldc/rust-projects/DD_Monitor/VideoWidget_vlc.py", line 767, in stopDanmuMessage
>     self.danmu.message.disconnect(self.playDanmu)
> TypeError: 'method' object is not connected
> 2021-02-05 20:39:00,442 [MainThread  ] [ERROR]  停止弹幕出错
> Traceback (most recent call last):
>   File "/home/oldc/rust-projects/DD_Monitor/VideoWidget_vlc.py", line 882, in setMedia
>     self.danmu.message.disconnect(self.playDanmu)
> TypeError: 'method' object is not connected
> 2021-02-05 20:39:00,443 [Dummy-5     ] [INFO ]  尝试打开 10209381 的弹幕Socket
> [NULL @ 0x7f81e1217140] Invalid NAL unit size (94522 > 39906).
> [NULL @ 0x7f81e1217140] missing picture in access unit with size 40057
> [h264 @ 0x7f81e1217140] Invalid NAL unit size (94522 > 39906).
> [h264 @ 0x7f81e1217140] Error splitting the input into NAL units.
> [h264 @ 0x7f81e0dbec00] Invalid NAL unit size (94522 > 39906).
> [h264 @ 0x7f81e0dbec00] Error splitting the input into NAL units.
> [00007f82481e5260] gl gl: Initialized libplacebo v2.72.0 (API v72)
> [00007f82481e5260] gl gl: Initialized libplacebo v2.72.0 (API v72)
> [00007f82481e5260] gl gl: Initialized libplacebo v2.72.0 (API v72)
> 2021-02-05 20:39:37,158 [MainThread  ] [INFO ]  exchange:0:21396545
> 2021-02-05 20:39:37,159 [MainThread  ] [INFO ]  
> 2021-02-05 20:39:37,159 [MainThread  ] [INFO ]  0
> 2021-02-05 20:39:37,159 [MainThread  ] [INFO ]   
> 2021-02-05 20:39:37,160 [MainThread  ] [INFO ]  0
> 2021-02-05 20:39:37,160 [MainThread  ] [INFO ]  
> [h264 @ 0x7f81a8080e80] get_buffer() failed
> [h264 @ 0x7f81a8080e80] thread_get_buffer() failed
> [h264 @ 0x7f81a8080e80] decode_slice_header error
> [h264 @ 0x7f81a8080e80] no frame!
> [h264 @ 0x7f81a809d940] get_buffer() failed
> [h264 @ 0x7f81a809d940] thread_get_buffer() failed
> [h264 @ 0x7f81a809d940] decode_slice_header error
> [h264 @ 0x7f81a809d940] no frame!
> [h264 @ 0x7f8278154200] get_buffer() failed
> [h264 @ 0x7f8278154200] thread_get_buffer() failed
> [h264 @ 0x7f8278154200] decode_slice_header error
> [h264 @ 0x7f8278154200] no frame!
> [h264 @ 0x7f8278065e00] get_buffer() failed
> [h264 @ 0x7f8278065e00] thread_get_buffer() failed
> [h264 @ 0x7f8278065e00] decode_slice_header error
> [h264 @ 0x7f8278065e00] no frame!
> 2021-02-05 20:39:56,066 [MainThread  ] [INFO ]  21547895 进入悬浮窗模式, 弹幕?: True
> 2021-02-05 20:39:57,073 [MainThread  ] [ERROR]  停止弹幕出错
> Traceback (most recent call last):
>   File "/home/oldc/rust-projects/DD_Monitor/VideoWidget_vlc.py", line 882, in setMedia
>     self.danmu.message.disconnect(self.playDanmu)
> TypeError: 'method' object is not connected
> [NULL @ 0x7f81b01a46c0] Invalid NAL unit size (54231 > 48096).
> [NULL @ 0x7f81b01a46c0] missing picture in access unit with size 48248
> [h264 @ 0x7f81b01a46c0] Invalid NAL unit size (54231 > 48096).
> [h264 @ 0x7f81b01a46c0] Error splitting the input into NAL units.
> [h264 @ 0x7f81b01790c0] Invalid NAL unit size (54231 > 48096).
> [h264 @ 0x7f81b01790c0] Error splitting the input into NAL units.
> [000055555b4f0ae0] gl gl: Initialized libplacebo v2.72.0 (API v72)
> [000055555b4f0ae0] gl gl: Initialized libplacebo v2.72.0 (API v72)
> [000055555b4f0ae0] gl gl: Initialized libplacebo v2.72.0 (API v72)
> 2021-02-05 20:40:20,790 [Dummy-6     ] [INFO ]  尝试打开 21547895 的弹幕Socket
> 2021-02-05 20:40:21,475 [Dummy-6     ] [INFO ]  尝试打开 21547895 的弹幕Socket
> QThread::start: Thread termination error (没有那个进程)
> 2021-02-05 20:40:22,412 [Dummy-6     ] [INFO ]  尝试打开 21547895 的弹幕Socket
> [1]    251744 killed     python3 DD监控室.py
>

**Comment by ssysm** [comment]
弹幕机无法同时置顶是个已知Bug，*inx系统的窗口排序与Windows不同。

关闭悬浮窗会卡死问题回头看下
