### ISSUE TITLE
错误报告

### ISSUE THREAD

**Issue by LONGATLer** [zhimingshenjun/DD_Monitor#81]
2021-02-07 21:47:57,320 [MainThread  ] [INFO ]  系统信息: 

主机名:           LAPTOP-H25U8L4R
OS 名称:          Microsoft Windows 10 家庭中文版
OS 版本:          10.0.18363 暂缺 Build 18363
OS 制造商:        Microsoft Corporation
OS 配置:          独立工作站
OS 构建类型:      Multiprocessor Free
注册的所有人:     13213505017@163.com
注册的组织:       暂缺
产品 ID:          00342-35979-72097-AAOEM
初始安装日期:     2020/12/10 星期四, 11:48:30
系统启动时间:     2021/2/7 星期日, 13:24:55
系统制造商:       LENOVO
系统型号:         82GR
系统类型:         x64-based PC
处理器:           安装了 1 个处理器。
                  [01]: AMD64 Family 23 Model 96 Stepping 1 AuthenticAMD ~2900 Mhz
BIOS 版本:        LENOVO FSCN11WW, 2020/7/23 星期四
Windows 目录:     C:\Windows
系统目录:         C:\Windows\system32
启动设备:         \Device\HarddiskVolume1
系统区域设置:     zh-cn;中文(中国)
输入法区域设置:   zh-cn;中文(中国)
时区:             (UTC+08:00) 北京，重庆，香港特别行政区，乌鲁木齐
物理内存总量:     16,253 MB
可用的物理内存:   10,264 MB
虚拟内存: 最大值: 18,685 MB
虚拟内存: 可用:   9,552 MB
虚拟内存: 使用中: 9,133 MB
页面文件位置:     C:\pagefile.sys
域:               WORKGROUP
登录服务器:       \\LAPTOP-H25U8L4R
修补程序:         安装了 11 个修补程序。
                  [01]: KB4586878
                  [02]: KB4513661
                  [03]: KB4516115
                  [04]: KB4517245
                  [05]: KB4521863
                  [06]: KB4535680
                  [07]: KB4560959
                  [08]: KB4580325
                  [09]: KB4586863
                  [10]: KB4598479
                  [11]: KB4598229
网卡:             安装了 5 个 NIC。
                  [01]: Realtek PCIe GbE Family Controller
                      连接名:      以太网
                      状态:        媒体连接已中断
                  [02]: Bluetooth Device (Personal Area Network)
                      连接名:      蓝牙网络连接
                      状态:        媒体连接已中断
                  [03]: Intel(R) Wi-Fi 6 AX200 160MHz
                      连接名:      WLAN
                      启用 DHCP:   是
                      DHCP 服务器: 192.168.31.1
                      IP 地址
                        [01]: 192.168.31.231
                        [02]: fe80::b968:7571:c3df:a2eb
                  [04]: Microsoft Wi-Fi Direct Virtual Adapter
                      连接名:      本地连接* 2
                      启用 DHCP:   否
                      IP 地址
                        [01]: 192.168.137.1
                        [02]: fe80::91da:e797:f5:596b
                  [05]: VirtualBox Host-Only Ethernet Adapter
                      连接名:      VirtualBox Host-Only Network
                      启用 DHCP:   否
                      IP 地址
                        [01]: 192.168.56.1
                        [02]: fe80::30b6:b619:77d7:3423
Hyper-V 要求:     虚拟机监视器模式扩展: 是
                  固件中已启用虚拟化: 是
                  二级地址转换: 是
                  数据执行保护可用: 是

2021-02-07 21:47:57,320 [MainThread  ] [INFO ]  GPU信息: 
AdapterCompatibility=NVIDIA
Caption=NVIDIA GeForce RTX 2060
DeviceID=VideoController1
DriverDate=20210122000000.000000-000
DriverVersion=27.21.14.6140
VideoModeDescription=1920 x 1080 x 4294967296 种颜色
2021-02-07 21:47:57,321 [MainThread  ] [INFO ]  libvlc env: PYTHON_VLC_LIB_PATH=
2021-02-07 21:47:57,321 [MainThread  ] [INFO ]  plugin env: PYTHON_VLC_MODULE_PATH=
2021-02-07 21:47:57,321 [MainThread  ] [INFO ]  libvlc path: D:\F\DD监控室v2.1 (VLC3.0内核)\libvlc.dll
2021-02-07 21:47:57,321 [MainThread  ] [INFO ]  vlc version: b'3.0.12 Vetinari'
2021-02-07 21:47:57,979 [MainThread  ] [INFO ]  嵌入窗0 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-07 21:47:58,009 [MainThread  ] [INFO ]  悬浮窗9 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-07 21:47:58,022 [MainThread  ] [INFO ]  VLC设置完毕 1 / 9
2021-02-07 21:47:58,047 [MainThread  ] [INFO ]  嵌入窗1 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-07 21:47:58,072 [MainThread  ] [INFO ]  悬浮窗10 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-07 21:47:58,077 [MainThread  ] [INFO ]  VLC设置完毕 2 / 9
2021-02-07 21:47:58,100 [MainThread  ] [INFO ]  嵌入窗2 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-07 21:47:58,124 [MainThread  ] [INFO ]  悬浮窗11 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-07 21:47:58,131 [MainThread  ] [INFO ]  VLC设置完毕 3 / 9
2021-02-07 21:47:58,156 [MainThread  ] [INFO ]  嵌入窗3 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-07 21:47:58,182 [MainThread  ] [INFO ]  悬浮窗12 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-07 21:47:58,189 [MainThread  ] [INFO ]  VLC设置完毕 4 / 9
2021-02-07 21:47:58,213 [MainThread  ] [INFO ]  嵌入窗4 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-07 21:47:58,237 [MainThread  ] [INFO ]  悬浮窗13 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-07 21:47:58,241 [MainThread  ] [INFO ]  VLC设置完毕 5 / 9
2021-02-07 21:47:58,267 [MainThread  ] [INFO ]  嵌入窗5 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-07 21:47:58,294 [MainThread  ] [INFO ]  悬浮窗14 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-07 21:47:58,299 [MainThread  ] [INFO ]  VLC设置完毕 6 / 9
2021-02-07 21:47:58,321 [MainThread  ] [INFO ]  嵌入窗6 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-07 21:47:58,346 [MainThread  ] [INFO ]  悬浮窗15 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-07 21:47:58,349 [MainThread  ] [INFO ]  VLC设置完毕 7 / 9
2021-02-07 21:47:58,381 [MainThread  ] [INFO ]  嵌入窗7 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-07 21:47:58,408 [MainThread  ] [INFO ]  悬浮窗16 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-07 21:47:58,414 [MainThread  ] [INFO ]  VLC设置完毕 8 / 9
2021-02-07 21:47:58,438 [MainThread  ] [INFO ]  嵌入窗8 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-07 21:47:58,463 [MainThread  ] [INFO ]  悬浮窗17 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-07 21:47:58,467 [MainThread  ] [INFO ]  VLC设置完毕 9 / 9
2021-02-07 21:47:58,677 [MainThread  ] [INFO ]  UI构造完毕
2021-02-07 21:47:58,847 [Dummy-1     ] [INFO ]  弹幕IP: 120.92.112.150
2021-02-07 21:48:37,322 [MainThread  ] [INFO ]  exchange:0:22696653
2021-02-07 21:48:37,322 [MainThread  ] [INFO ]  
2021-02-07 21:48:37,322 [MainThread  ] [INFO ]  0
2021-02-07 21:48:37,322 [MainThread  ] [INFO ]   
2021-02-07 21:48:37,322 [MainThread  ] [INFO ]  0
2021-02-07 21:48:37,323 [MainThread  ] [INFO ]  
2021-02-07 21:48:38,083 [MainThread  ] [INFO ]  exchange:0:22696653
2021-02-07 21:48:38,083 [MainThread  ] [INFO ]  
2021-02-07 21:48:38,083 [MainThread  ] [INFO ]  0
2021-02-07 21:48:38,083 [MainThread  ] [INFO ]   
2021-02-07 21:48:38,083 [MainThread  ] [INFO ]  0
2021-02-07 21:48:38,083 [MainThread  ] [INFO ]  
2021-02-07 21:48:40,138 [MainThread  ] [INFO ]  roomID:3044248
2021-02-07 21:48:40,138 [MainThread  ] [INFO ]  
2021-02-07 21:48:40,138 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 767, in stopDanmuMessage
TypeError: 'method' object is not connected
2021-02-07 21:48:44,882 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 882, in setMedia
TypeError: 'method' object is not connected
2021-02-07 21:48:44,884 [Dummy-2     ] [INFO ]  尝试打开 3044248 的弹幕Socket
2021-02-07 21:48:45,091 [MainThread  ] [INFO ]  exchange:0:3044248
2021-02-07 21:48:45,091 [MainThread  ] [INFO ]  
2021-02-07 21:48:45,091 [MainThread  ] [INFO ]  0
2021-02-07 21:48:45,091 [MainThread  ] [INFO ]   
2021-02-07 21:48:45,091 [MainThread  ] [INFO ]  0
2021-02-07 21:48:45,091 [MainThread  ] [INFO ]  
2021-02-07 21:48:51,155 [MainThread  ] [INFO ]  roomID:704808
2021-02-07 21:48:51,155 [MainThread  ] [INFO ]  
2021-02-07 21:48:51,155 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 767, in stopDanmuMessage
TypeError: 'method' object is not connected
2021-02-07 21:48:53,282 [MainThread  ] [INFO ]  roomID:21463219
2021-02-07 21:48:53,282 [MainThread  ] [INFO ]  
2021-02-07 21:48:53,282 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 767, in stopDanmuMessage
TypeError: 'method' object is not connected
2021-02-07 21:48:54,060 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 882, in setMedia
TypeError: 'method' object is not connected
2021-02-07 21:48:54,063 [Dummy-3     ] [INFO ]  尝试打开 21463219 的弹幕Socket
2021-02-07 21:48:54,868 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 882, in setMedia
TypeError: 'method' object is not connected
2021-02-07 21:48:54,870 [Dummy-4     ] [INFO ]  尝试打开 704808 的弹幕Socket
2021-02-07 21:49:09,843 [MainThread  ] [INFO ]  roomID:22470202
2021-02-07 21:49:09,844 [MainThread  ] [INFO ]  
2021-02-07 21:49:09,844 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 767, in stopDanmuMessage
TypeError: 'method' object is not connected
2021-02-07 21:49:10,818 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 882, in setMedia
TypeError: 'method' object is not connected
2021-02-07 21:49:10,822 [Dummy-5     ] [INFO ]  尝试打开 22470202 的弹幕Socket
2021-02-07 21:49:11,482 [MainThread  ] [INFO ]  roomID:21656036
2021-02-07 21:49:11,482 [MainThread  ] [INFO ]  
2021-02-07 21:49:11,483 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 767, in stopDanmuMessage
TypeError: 'method' object is not connected
2021-02-07 21:49:15,553 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 882, in setMedia
TypeError: 'method' object is not connected
2021-02-07 21:49:15,556 [Dummy-6     ] [INFO ]  尝试打开 21656036 的弹幕Socket
2021-02-07 21:49:19,539 [MainThread  ] [INFO ]  roomID:41682
2021-02-07 21:49:19,539 [MainThread  ] [INFO ]  
2021-02-07 21:49:19,539 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 767, in stopDanmuMessage
TypeError: 'method' object is not connected
2021-02-07 21:49:20,272 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 882, in setMedia
TypeError: 'method' object is not connected
2021-02-07 21:49:20,275 [Dummy-7     ] [INFO ]  尝试打开 41682 的弹幕Socket
2021-02-07 21:49:20,941 [MainThread  ] [INFO ]  roomID:14327465
2021-02-07 21:49:20,941 [MainThread  ] [INFO ]  
2021-02-07 21:49:20,941 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 767, in stopDanmuMessage
TypeError: 'method' object is not connected
2021-02-07 21:49:23,403 [MainThread  ] [INFO ]  roomID:22384516
2021-02-07 21:49:23,403 [MainThread  ] [INFO ]  
2021-02-07 21:49:23,403 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 767, in stopDanmuMessage
TypeError: 'method' object is not connected
2021-02-07 21:49:24,644 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 882, in setMedia
TypeError: 'method' object is not connected
2021-02-07 21:49:24,661 [Dummy-8     ] [INFO ]  尝试打开 14327465 的弹幕Socket
2021-02-07 21:49:25,220 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 882, in setMedia
TypeError: 'method' object is not connected
2021-02-07 21:49:25,223 [Dummy-9     ] [INFO ]  尝试打开 22384516 的弹幕Socket
2021-02-07 21:49:55,242 [MainThread  ] [INFO ]  3044248 进入悬浮窗模式, 弹幕?: True
2021-02-07 21:49:56,221 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 882, in setMedia
TypeError: 'method' object is not connected
2021-02-07 21:49:58,756 [MainThread  ] [INFO ]  
2021-02-07 21:50:02,544 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 866, in mediaStop
TypeError: 'method' object is not connected
2021-02-07 21:50:03,072 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 882, in setMedia
TypeError: 'method' object is not connected
2021-02-07 21:50:03,075 [Dummy-10    ] [INFO ]  尝试打开 3044248 的弹幕Socket
2021-02-07 21:51:08,140 [Dummy-11    ] [ERROR]  
************!!!UNCAUGHT EXCEPTION!!!*********************
Type: <class 'requests.exceptions.ConnectionError'>
Value: HTTPSConnectionPool(host='i0.hdslb.com', port=443): Max retries exceeded with url: /bfs/live/keyframe02072147000022384516vxdi43.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000170D34D0208>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Traceback:
  File "LiverSelect.py", line 175, in run
   File "site-packages\requests\api.py", line 76, in get
   File "site-packages\requests\api.py", line 61, in request
   File "site-packages\requests\sessions.py", line 530, in request
   File "site-packages\requests\sessions.py", line 643, in send
   File "site-packages\requests\adapters.py", line 516, in send
************************************************************

2021-02-07 21:52:43,688 [Dummy-12    ] [ERROR]  
************!!!UNCAUGHT EXCEPTION!!!*********************
Type: <class 'requests.exceptions.ConnectionError'>
Value: HTTPSConnectionPool(host='i0.hdslb.com', port=443): Max retries exceeded with url: /bfs/live/keyframe02072147000014327465zvm67g.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000170D34E6C48>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Traceback:
  File "LiverSelect.py", line 175, in run
   File "site-packages\requests\api.py", line 76, in get
   File "site-packages\requests\api.py", line 61, in request
   File "site-packages\requests\sessions.py", line 530, in request
   File "site-packages\requests\sessions.py", line 643, in send
   File "site-packages\requests\adapters.py", line 516, in send
************************************************************

2021-02-07 21:56:38,672 [Dummy-13    ] [ERROR]  
************!!!UNCAUGHT EXCEPTION!!!*********************
Type: <class 'requests.exceptions.ConnectionError'>
Value: HTTPSConnectionPool(host='i0.hdslb.com', port=443): Max retries exceeded with url: /bfs/live/keyframe02072152000022386431dlsv5v.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000170D24F1BC8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
Traceback:
  File "LiverSelect.py", line 175, in run
   File "site-packages\requests\api.py", line 76, in get
   File "site-packages\requests\api.py", line 61, in request
   File "site-packages\requests\sessions.py", line 530, in request
   File "site-packages\requests\sessions.py", line 643, in send
   File "site-packages\requests\adapters.py", line 516, in send
************************************************************

2021-02-07 21:56:52,590 [Dummy-14    ] [ERROR]  [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'D:\\F\\DD监控室v2.1 (VLC3.0内核)\\cache/1612705674/2.flv'
2021-02-07 21:56:53,168 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 866, in mediaStop
TypeError: 'method' object is not connected
2021-02-07 21:56:53,170 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 866, in mediaStop
TypeError: 'method' object is not connected
2021-02-07 21:56:53,172 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 866, in mediaStop
TypeError: 'method' object is not connected
2021-02-07 21:56:53,174 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 866, in mediaStop
TypeError: 'method' object is not connected
2021-02-07 21:56:53,176 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 866, in mediaStop
TypeError: 'method' object is not connected
2021-02-07 21:56:53,178 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 866, in mediaStop
TypeError: 'method' object is not connected
2021-02-07 21:56:53,180 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 866, in mediaStop
TypeError: 'method' object is not connected
2021-02-07 21:56:53,182 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 866, in mediaStop
TypeError: 'method' object is not connected
2021-02-07 21:56:53,184 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 866, in mediaStop
TypeError: 'method' object is not connected
2021-02-07 21:56:53,186 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 866, in mediaStop
TypeError: 'method' object is not connected
2021-02-07 21:56:53,188 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 866, in mediaStop
TypeError: 'method' object is not connected
2021-02-07 21:56:53,190 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 866, in mediaStop
TypeError: 'method' object is not connected
2021-02-07 21:56:53,192 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 866, in mediaStop
TypeError: 'method' object is not connected
2021-02-07 21:56:53,194 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 866, in mediaStop
TypeError: 'method' object is not connected
2021-02-07 21:56:53,196 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 866, in mediaStop
TypeError: 'method' object is not connected
2021-02-07 21:56:53,197 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 866, in mediaStop
TypeError: 'method' object is not connected
2021-02-07 21:56:53,199 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 866, in mediaStop
TypeError: 'method' object is not connected
2021-02-07 21:56:53,201 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 866, in mediaStop
TypeError: 'method' object is not connected
2021-02-07 21:56:53,203 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 866, in mediaStop
TypeError: 'method' object is not connected
[log-2021-02-07.txt](https://github.com/zhimingshenjun/DD_Monitor/files/5939125/log-2021-02-07.txt)

**Comment by ssysm** [comment]
解决办法同 #80
