### ISSUE TITLE
错误报告

### ISSUE THREAD

**Issue by X-Jackdaw** [zhimingshenjun/DD_Monitor#88]
2021-02-13 22:40:04,818 [MainThread  ] [INFO ]  系统信息: 

主机名:           MI
OS 名称:          Microsoft Windows 10 家庭版
OS 版本:          10.0.19042 暂缺 Build 19042
OS 制造商:        Microsoft Corporation
OS 配置:          独立工作站
OS 构建类型:      Multiprocessor Free
注册的所有人:     暂缺
注册的组织:       暂缺
产品 ID:          00326-10000-00000-AA738
初始安装日期:     2020/12/29, 15:19:47
系统启动时间:     2021/2/13, 8:14:51
系统制造商:       Timi
系统型号:         TM1701
系统类型:         x64-based PC
处理器:           安装了 1 个处理器。
                  [01]: Intel64 Family 6 Model 142 Stepping 10 GenuineIntel ~1600 Mhz
BIOS 版本:        INSYDE Corp. XMAKB5R0P0502, 2017/10/13
Windows 目录:     C:\WINDOWS
系统目录:         C:\WINDOWS\system32
启动设备:         \Device\HarddiskVolume1
系统区域设置:     zh-cn;中文(中国)
输入法区域设置:   zh-cn;中文(中国)
时区:             (UTC+08:00) 北京，重庆，香港特别行政区，乌鲁木齐
物理内存总量:     8,076 MB
可用的物理内存:   4,686 MB
虚拟内存: 最大值: 15,500 MB
虚拟内存: 可用:   9,240 MB
虚拟内存: 使用中: 6,260 MB
页面文件位置:     C:\pagefile.sys
域:               WORKGROUP
登录服务器:       \\MI
修补程序:         安装了 9 个修补程序。
                  [01]: KB4601050
                  [02]: KB4562830
                  [03]: KB4570334
                  [04]: KB4580325
                  [05]: KB4586864
                  [06]: KB4593175
                  [07]: KB4598481
                  [08]: KB4601319
                  [09]: KB4592784
网卡:             安装了 4 个 NIC。
                  [01]: Intel(R) Dual Band Wireless-AC 8265
                      连接名:      WLAN
                      启用 DHCP:   是
                      DHCP 服务器: 10.10.10.1
                      IP 地址
                        [01]: 10.10.10.10
                        [02]: fe80::3ca3:6e11:cc2c:55b7
                  [02]: Bluetooth Device (Personal Area Network)
                      连接名:      蓝牙网络连接
                      状态:        媒体连接已中断
                  [03]: VMware Virtual Ethernet Adapter for VMnet1
                      连接名:      VMware Network Adapter VMnet1
                      启用 DHCP:   是
                      DHCP 服务器: 192.168.48.254
                      IP 地址
                        [01]: 192.168.48.1
                        [02]: fe80::4056:5fd1:0:69b8
                  [04]: VMware Virtual Ethernet Adapter for VMnet8
                      连接名:      VMware Network Adapter VMnet8
                      启用 DHCP:   是
                      DHCP 服务器: 192.168.44.254
                      IP 地址
                        [01]: 192.168.44.1
                        [02]: fe80::90c:90fc:139c:4bca
Hyper-V 要求:     虚拟机监视器模式扩展: 是
                  固件中已启用虚拟化: 是
                  二级地址转换: 是
                  数据执行保护可用: 是

2021-02-13 22:40:04,818 [MainThread  ] [INFO ]  GPU信息: 
AdapterCompatibility=NVIDIA
Caption=NVIDIA GeForce MX150
DeviceID=VideoController1
DriverDate=20210122000000.000000-000
DriverVersion=27.21.14.6140
VideoModeDescription=

AdapterCompatibility=Intel Corporation
Caption=Intel(R) UHD Graphics 620
DeviceID=VideoController2
DriverDate=20190109000000.000000-000
DriverVersion=25.20.100.6518
VideoModeDescription=1920 x 1080 x 4294967296 种颜色
2021-02-13 22:40:04,819 [MainThread  ] [INFO ]  libvlc env: PYTHON_VLC_LIB_PATH=
2021-02-13 22:40:04,819 [MainThread  ] [INFO ]  plugin env: PYTHON_VLC_MODULE_PATH=
2021-02-13 22:40:04,819 [MainThread  ] [INFO ]  libvlc path: E:\Tolls\Programs\DD\libvlc.dll
2021-02-13 22:40:04,819 [MainThread  ] [INFO ]  vlc version: b'3.0.12 Vetinari'
2021-02-13 22:40:05,841 [MainThread  ] [INFO ]  嵌入窗0 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-13 22:40:05,875 [MainThread  ] [INFO ]  悬浮窗9 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-13 22:40:05,893 [MainThread  ] [INFO ]  VLC设置完毕 1 / 9
2021-02-13 22:40:05,918 [MainThread  ] [INFO ]  嵌入窗1 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-13 22:40:05,947 [MainThread  ] [INFO ]  悬浮窗10 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-13 22:40:05,954 [MainThread  ] [INFO ]  VLC设置完毕 2 / 9
2021-02-13 22:40:05,977 [MainThread  ] [INFO ]  嵌入窗2 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-13 22:40:06,009 [MainThread  ] [INFO ]  悬浮窗11 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-13 22:40:06,018 [MainThread  ] [INFO ]  VLC设置完毕 3 / 9
2021-02-13 22:40:06,041 [MainThread  ] [INFO ]  嵌入窗3 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-13 22:40:06,077 [MainThread  ] [INFO ]  悬浮窗12 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-13 22:40:06,087 [MainThread  ] [INFO ]  VLC设置完毕 4 / 9
2021-02-13 22:40:06,115 [MainThread  ] [INFO ]  嵌入窗4 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-13 22:40:06,146 [MainThread  ] [INFO ]  悬浮窗13 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-13 22:40:06,151 [MainThread  ] [INFO ]  VLC设置完毕 5 / 9
2021-02-13 22:40:06,176 [MainThread  ] [INFO ]  嵌入窗5 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-13 22:40:06,206 [MainThread  ] [INFO ]  悬浮窗14 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-13 22:40:06,212 [MainThread  ] [INFO ]  VLC设置完毕 6 / 9
2021-02-13 22:40:06,238 [MainThread  ] [INFO ]  嵌入窗6 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-13 22:40:06,269 [MainThread  ] [INFO ]  悬浮窗15 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-13 22:40:06,274 [MainThread  ] [INFO ]  VLC设置完毕 7 / 9
2021-02-13 22:40:06,302 [MainThread  ] [INFO ]  嵌入窗7 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-13 22:40:06,331 [MainThread  ] [INFO ]  悬浮窗16 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-13 22:40:06,339 [MainThread  ] [INFO ]  VLC设置完毕 8 / 9
2021-02-13 22:40:06,368 [MainThread  ] [INFO ]  嵌入窗8 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-13 22:40:06,397 [MainThread  ] [INFO ]  悬浮窗17 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-13 22:40:06,405 [MainThread  ] [INFO ]  VLC设置完毕 9 / 9
2021-02-13 22:40:06,646 [MainThread  ] [INFO ]  UI构造完毕
2021-02-13 22:40:06,821 [Dummy-1     ] [INFO ]  弹幕IP: 120.92.144.250
2021-02-13 22:40:08,175 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 882, in setMedia
TypeError: 'method' object is not connected
2021-02-13 22:40:08,192 [Dummy-2     ] [INFO ]  尝试打开 8725120 的弹幕Socket
2021-02-13 22:40:08,359 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 882, in setMedia
TypeError: 'method' object is not connected
2021-02-13 22:40:08,365 [Dummy-3     ] [INFO ]  尝试打开 22727121 的弹幕Socket
2021-02-13 22:40:08,635 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 882, in setMedia
TypeError: 'method' object is not connected
2021-02-13 22:40:08,637 [Dummy-4     ] [INFO ]  尝试打开 14327465 的弹幕Socket
2021-02-13 22:40:09,341 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 882, in setMedia
TypeError: 'method' object is not connected
2021-02-13 22:40:09,348 [Dummy-5     ] [INFO ]  尝试打开 14052636 的弹幕Socket
2021-02-13 22:40:26,381 [MainThread  ] [INFO ]  exchange:0:8725120
2021-02-13 22:40:26,381 [MainThread  ] [INFO ]  
2021-02-13 22:40:26,383 [MainThread  ] [INFO ]  0
2021-02-13 22:40:26,383 [MainThread  ] [INFO ]   
2021-02-13 22:40:26,383 [MainThread  ] [INFO ]  0
2021-02-13 22:40:26,383 [MainThread  ] [INFO ]  
2021-02-13 22:42:57,608 [MainThread  ] [INFO ]  roomID:704808
2021-02-13 22:42:57,608 [MainThread  ] [INFO ]  
2021-02-13 22:42:58,732 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 882, in setMedia
TypeError: 'method' object is not connected
2021-02-13 22:42:58,739 [Dummy-6     ] [INFO ]  尝试打开 704808 的弹幕Socket
2021-02-13 22:44:11,095 [Dummy-7     ] [INFO ]  尝试打开 8725120 的弹幕Socket
2021-02-13 22:44:11,457 [Dummy-8     ] [INFO ]  尝试打开 22727121 的弹幕Socket
2021-02-13 22:44:11,788 [Dummy-9     ] [INFO ]  尝试打开 14327465 的弹幕Socket
2021-02-13 22:44:12,076 [Dummy-10    ] [INFO ]  尝试打开 704808 的弹幕Socket
2021-02-13 22:44:40,906 [MainThread  ] [INFO ]  exchange:0:8725120
2021-02-13 22:44:40,906 [MainThread  ] [INFO ]  
2021-02-13 22:44:40,906 [MainThread  ] [INFO ]  0
2021-02-13 22:44:40,906 [MainThread  ] [INFO ]   
2021-02-13 22:44:40,906 [MainThread  ] [INFO ]  0
2021-02-13 22:44:40,906 [MainThread  ] [INFO ]  
2021-02-13 22:46:49,407 [Dummy-11    ] [ERROR]  房间信息获取失败
Traceback (most recent call last):
  File "site-packages\urllib3\connectionpool.py", line 667, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 930, in _prepare_proxy
  File "site-packages\urllib3\connection.py", line 370, in connect
  File "site-packages\urllib3\util\ssl_.py", line 377, in ssl_wrap_socket
  File "ssl.py", line 423, in wrap_socket
  File "ssl.py", line 870, in _create
  File "ssl.py", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\requests\adapters.py", line 449, in send
  File "site-packages\urllib3\connectionpool.py", line 725, in urlopen
  File "site-packages\urllib3\util\retry.py", line 439, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.live.bilibili.com', port=443): Max retries exceeded with url: /xlive/web-interface/v1/second/getList?platform=web&parent_area_id=1&page=3 (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "LiverSelect.py", line 412, in run
  File "site-packages\requests\api.py", line 76, in get
  File "site-packages\requests\api.py", line 61, in request
  File "site-packages\requests\sessions.py", line 530, in request
  File "site-packages\requests\sessions.py", line 643, in send
  File "site-packages\requests\adapters.py", line 510, in send
requests.exceptions.ProxyError: HTTPSConnectionPool(host='api.live.bilibili.com', port=443): Max retries exceeded with url: /xlive/web-interface/v1/second/getList?platform=web&parent_area_id=1&page=3 (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))
2021-02-13 22:47:24,524 [Dummy-12    ] [ERROR]  HTTPSConnectionPool(host='api.live.bilibili.com', port=443): Max retries exceeded with url: /room/v1/Room/get_status_info_by_uids (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))
2021-02-13 22:54:39,536 [MainThread  ] [INFO ]  8725120 进入悬浮窗模式, 弹幕?: True
2021-02-13 22:54:40,851 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 882, in setMedia
TypeError: 'method' object is not connected
2021-02-13 22:54:44,091 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 866, in mediaStop
TypeError: 'method' object is not connected
2021-02-13 22:54:44,766 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 882, in setMedia
TypeError: 'method' object is not connected
2021-02-13 22:54:44,766 [Dummy-13    ] [INFO ]  尝试打开 8725120 的弹幕Socket
2021-02-13 22:54:46,002 [MainThread  ] [INFO ]  exchange:0:8725120
2021-02-13 22:54:46,002 [MainThread  ] [INFO ]  
2021-02-13 22:54:46,002 [MainThread  ] [INFO ]  0
2021-02-13 22:54:46,002 [MainThread  ] [INFO ]   
2021-02-13 22:54:46,002 [MainThread  ] [INFO ]  0
2021-02-13 22:54:46,002 [MainThread  ] [INFO ]  
2021-02-13 22:54:52,528 [MainThread  ] [INFO ]  exchange:0:8725120
2021-02-13 22:54:52,531 [MainThread  ] [INFO ]  
2021-02-13 22:54:52,531 [MainThread  ] [INFO ]  0
2021-02-13 22:54:52,531 [MainThread  ] [INFO ]   
2021-02-13 22:54:52,531 [MainThread  ] [INFO ]  0
2021-02-13 22:54:52,531 [MainThread  ] [INFO ]  
2021-02-13 22:55:09,565 [Dummy-14    ] [INFO ]  尝试打开 704808 的弹幕Socket
2021-02-13 22:55:25,231 [Dummy-15    ] [ERROR]  HTTPSConnectionPool(host='api.live.bilibili.com', port=443): Max retries exceeded with url: /room/v2/Room/get_by_ids (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))
2021-02-13 22:57:02,476 [Dummy-16    ] [ERROR]  HTTPSConnectionPool(host='d1--cn-gotcha04.bilivideo.com', port=443): Max retries exceeded with url: /live-bvc/255115/live_18149131_9762681.flv?cdn=cn-gotcha04&expires=1613231817&len=0&oi=3083214136&pt=web&qn=10000&trid=adfa1fc7d83a4f849949bcfd52b8ca49&sigparams=cdn,expires,len,oi,pt,qn,trid&sign=595a147a0bd21923e90083d8ba7e0397&ptype=0&src=9&sl=4&order=1 (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))
2021-02-13 22:57:02,477 [Dummy-16    ] [ERROR]  直播地址获取失败 / 缓存视频出错
Traceback (most recent call last):
  File "site-packages\urllib3\connectionpool.py", line 667, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 930, in _prepare_proxy
  File "site-packages\urllib3\connection.py", line 370, in connect
  File "site-packages\urllib3\util\ssl_.py", line 377, in ssl_wrap_socket
  File "ssl.py", line 423, in wrap_socket
  File "ssl.py", line 870, in _create
  File "ssl.py", line 1139, in do_handshake
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\requests\adapters.py", line 449, in send
  File "site-packages\urllib3\connectionpool.py", line 725, in urlopen
  File "site-packages\urllib3\util\retry.py", line 439, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='d1--cn-gotcha04.bilivideo.com', port=443): Max retries exceeded with url: /live-bvc/255115/live_18149131_9762681.flv?cdn=cn-gotcha04&expires=1613231817&len=0&oi=3083214136&pt=web&qn=10000&trid=adfa1fc7d83a4f849949bcfd52b8ca49&sigparams=cdn,expires,len,oi,pt,qn,trid&sign=595a147a0bd21923e90083d8ba7e0397&ptype=0&src=9&sl=4&order=1 (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 94, in run
  File "site-packages\requests\api.py", line 76, in get
  File "site-packages\requests\api.py", line 61, in request
  File "site-packages\requests\sessions.py", line 530, in request
  File "site-packages\requests\sessions.py", line 643, in send
  File "site-packages\requests\adapters.py", line 510, in send
requests.exceptions.ProxyError: HTTPSConnectionPool(host='d1--cn-gotcha04.bilivideo.com', port=443): Max retries exceeded with url: /live-bvc/255115/live_18149131_9762681.flv?cdn=cn-gotcha04&expires=1613231817&len=0&oi=3083214136&pt=web&qn=10000&trid=adfa1fc7d83a4f849949bcfd52b8ca49&sigparams=cdn,expires,len,oi,pt,qn,trid&sign=595a147a0bd21923e90083d8ba7e0397&ptype=0&src=9&sl=4&order=1 (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))
2021-02-13 22:59:09,061 [MainThread  ] [ERROR]  
************!!!UNCAUGHT EXCEPTION!!!*********************
Type: <class 'requests.exceptions.ProxyError'>
Value: HTTPSConnectionPool(host='api.live.bilibili.com', port=443): Max retries exceeded with url: /xlive/web-room/v1/index/getInfoByRoom?room_id=704808 (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))
Traceback:
  File "VideoWidget_vlc.py", line 847, in mediaReload
   File "VideoWidget_vlc.py", line 956, in setTitle
   File "site-packages\requests\api.py", line 76, in get
   File "site-packages\requests\api.py", line 61, in request
   File "site-packages\requests\sessions.py", line 530, in request
   File "site-packages\requests\sessions.py", line 643, in send
   File "site-packages\requests\adapters.py", line 510, in send
************************************************************

**Comment by ssysm** [comment]
2.2版已解决， #80 。从Actions里面下一个就好

https://github.com/zhimingshenjun/DD_Monitor/issues/80#issuecomment-774676764
