### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by chanchancl** [zhimingshenjun/DD_Monitor#9]
一晚上一直是这样，看一段时间，就直接退出了

大概十分钟多一点

win10 64位，2004. 19041.746

**Comment by inkydragon** [comment]
看了一眼，目前没有记录日志。闪退这种 bug 就有点难搞了。

**Comment by zhimingshenjun** [comment]
闪退现在debug下来 主要是由于用户电脑的渲染器设置导致的 这种很难debug 我也还在看




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhimingshenjun/DD_Monitor"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月24日(星期天) 晚上11:57
收件人:&nbsp;"zhimingshenjun/DD_Monitor"<DD_Monitor@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [zhimingshenjun/DD_Monitor] 闪退 (#9)





 
看了一眼，目前没有记录日志。闪退这种 bug 就有点难搞了。

**Comment by zhimingshenjun** [comment]
我在视频评论区里列了大致的一些解决方案 可以试试

**Comment by chanchancl** [comment]
ok，今天回去尝试一下

**Comment by inkydragon** [comment]
昨天挂机 pycharm 控制台捕获的 stderr。
但我用的时候并没有闪退。

<details> 
<summary>stderr</summary> 

[000001bc4a736b20] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001bc4de2fa50] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001bc4dda2bc0] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001bc4de6a740] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001bc4de6aa60] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001bc4de697a0] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001bc4de6a100] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001bc4de6a420] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001bc4de68e40] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001bc4de69160] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001bc4de69480] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001bc4de69ac0] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001bc4de69de0] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001bc4dea64e0] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001bc4dea7480] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001bc4dea5540] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001bc4dea6b20] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001bc4dea48c0] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001bc4dea6800] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001bc4dea6e40] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001bc4dea4f00] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001bc4dea5220] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001bc4dea7160] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001bc4dea3f60] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001bc4dea4280] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001bc4dea77a0] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001bc4dea5ea0] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001bc4dea7ac0] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001bc4dea5860] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001bc4dea45a0] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001bc4dea4be0] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001bc4dea5b80] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001bc4dea61c0] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001bc4deca7e0] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001bc4decab00] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001bc4decae20] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001bc5309eac0] direct3d11 vout display error: SetThumbNailClip failed: 0x800706f4
[000001bc4de70a50] avcodec decoder: Using DXVA2 (Intel(R) HD Graphics 5500, vendor Intel(8086), device 1616, revision 9) for hardware decoding
[000001bc527d5f00] direct3d11 vout display error: SetThumbNailClip failed: 0x800706f4
[000001bc536d3ad0] avcodec decoder: Using DXVA2 (Intel(R) HD Graphics 5500, vendor Intel(8086), device 1616, revision 9) for hardware decoding
[000001bc539e97f0] direct3d11 vout display error: SetThumbNailClip failed: 0x800706f4
[000001bc536d33b0] avcodec decoder: Using DXVA2 (Intel(R) HD Graphics 5500, vendor Intel(8086), device 1616, revision 9) for hardware decoding
[h264 @ 000001bc4f410700] Invalid NAL unit size (14883 > 1034).
[h264 @ 000001bc4f410700] Error splitting the input into NAL units.
[000001bc539e9550] direct3d11 vout display error: SetThumbNailClip failed[WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'F:/vtb/DDMonitor\\cache/1611509997/0.flv'
[WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'F:/vtb/DDMonitor\\cache/1611509997/1.flv'
[WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'F:/vtb/DDMonitor\\cache/1611509997/2.flv'
[WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'F:/vtb/DDMonitor\\cache/1611509997/2.flv'
[WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'F:/vtb/DDMonitor\\cache/1611509997/1.flv'
[WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'F:/vtb/DDMonitor\\cache/1611509997/0.flv'
: 0x800706f4
[000001bc6d53bf60] direct3d11 vout display error: SetThumbNailClip failed: 0x800706f4
[000001bc53c73320] avcodec decoder: Using DXVA2 (Intel(R) HD Graphics 5500, vendor Intel(8086), device 1616, revision 9) for hardware decoding
[h264 @ 000001bc4df1fb00] illegal short term buffer state detected
[h264 @ 000001bc4df1c740] illegal short term buffer state detected
[000001bc5309eac0] direct3d11 vout display error: SetThumbNailClip failed: 0x800706f4
[000001bc537be5a0] direct3d11 vout display error: SetThumbNailClip failed: 0x800706f4
[000001bc6d53c200] direct3d11 vout display error: SetThumbNailClip failed: 0x800706f4
[000001bc536e2700] filesystem stream error: cannot open file F:\vtb\DDMonitor\cache\1611509997\1.flv (No such file or directory)
[000001bc537da7a0] main input error: 您的输入无法被打开
[000001bc537da7a0] main input error: VLC 无法打开 MRL「file:///F:/vtb/DDMonitor/cache/1611509997/1.flv」。详情请检查日志。
[000001bc7488f790] filesystem stream error: cannot open file F:\vtb\DDMonitor\cache\1611509997\2.flv (No such file or directory)
[000001bc537dbac0] main input error: 您的输入无法被打开
[000001bc537dbac0] main input error: VLC 无法打开 MRL「file:///F:/vtb/DDMonitor/cache/1611509997/2.flv」。详情请检查日志。
[000001bc5305c240] direct3d11 vout display error: SetThumbNailClip failed: 0x800706f4
[000001bc5267e960] avcodec decoder: Using DXVA2 (Intel(R) HD Graphics 5500, vendor Intel(8086), device 1616, revision 9) for hardware decoding
[NULL @ 000001bc535ab9c0] Invalid NAL unit size (521609 > 433207).
[NULL @ 000001bc535ab9c0] missing picture in access unit with size 433239
[h264 @ 000001bc535ab9c0] Invalid NAL unit size (521609 > 433207).
[h264 @ 000001bc535ab9c0] Error splitting the input into NAL units.
[h264 @ 000001bc535acf60] Invalid NAL unit size (521609 > 433207).
[h264 @ 000001bc535acf60] Error splitting the input into NAL units.
[000001bc5305c240] direct3d11 vout display error: SetThumbNailClip failed: 0x800706f4
[000001bc5267ecf0] avcodec decoder: Using DXVA2 (Intel(R) HD Graphics 5500, vendor Intel(8086), device 1616, revision 9) for hardware decoding
[NULL @ 000001bc535abe20] Invalid NAL unit size (521917 > 367671).
[NULL @ 000001bc535abe20] missing picture in access unit with size 367703
[h264 @ 000001bc535abe20] Invalid NAL unit size (521917 > 367671).
[h264 @ 000001bc535abe20] Error splitting the input into NAL units.
[000001bc5305ba60] direct3d11 vout display error: SetThumbNailClip failed: 0x800706f4
[000001bc5267e5d0] avcodec decoder: Using DXVA2 (Intel(R) HD Graphics 5500, vendor Intel(8086), device 1616, revision 9) for hardware decoding
[000001bc6dae0360] direct3d11 vout display error: SetThumbNailClip failed: 0x800706f4
[000001bc5305b280] direct3d11 vout display error: SetThumbNailClip failed: 0x800706f4
[000001bc5305b520] direct3d11 vout display error: SetThumbNailClip failed: 0x800706f4
[000001bc527cf880] avcodec decoder: Using D3D11VA (Intel(R) HD Graphics 5500, vendor 8086(Intel), device 1616, revision 9) for hardware decoding
[000001bc527cf160] avcodec decoder: Using D3D11VA (Intel(R) HD Graphics 5500, vendor 8086(Intel), device 1616, revision 9) for hardware decoding
[000001bc538bfdd0] avcodec decoder: Using D3D11VA (Intel(R) HD Graphics 5500, vendor 8086(Intel), device 1616, revision 9) for hardware decoding
[000001bc53905de0] direct3d11 vout display error: SetThumbNailClip failed: 0x800706f4
[h264 @ 000001bc14042fc0] get_buffer() failed
[h264 @ 000001bc14042fc0] thread_get_buffer() failed
[h264 @ 000001bc14042fc0] decode_slice_header error
[h264 @ 000001bc14042fc0] no frame!
[h264 @ 000001bc14045240] get_buffer() failed
[h264 @ 000001bc14045240] thread_get_buffer() failed
[h264 @ 000001bc14045240] decode_slice_header error
[h264 @ 000001bc14045240] no frame!
[000001bc53905600] direct3d11 vout display error: SetThumbNailClip failed: 0x800706f4
[h264 @ 000001bc4f0f1ae0] get_buffer() failed
[h264 @ 000001bc4f0f1ae0] thread_get_buffer() failed
[h264 @ 000001bc4f0f1ae0] decode_slice_header error
[h264 @ 000001bc4f0f1ae0] get_buffer() failed
[h264 @ 000001bc4f0f1ae0] thread_get_buffer() failed
[h264 @ 000001bc4f0f1ae0] decode_slice_header error
[h264 @ 000001bc1403f360] get_buffer() failed
[h264 @ 000001bc1403f360] thread_get_buffer() failed
[h264 @ 000001bc1403f360] decode_slice_header error
[h264 @ 000001bc1403f360] get_buffer() failed
[h264 @ 000001bc1403f360] thread_get_buffer() failed
[h264 @ 000001bc1403f360] decode_slice_header error
[h264 @ 000001bc1403f360] get_buffer() failed
[h264 @ 000001bc1403f360] thread_get_buffer() failed
[h264 @ 000001bc1403f360] decode_slice_header error
[h264 @ 000001bc1403f360] get_buffer() failed
[h264 @ 000001bc1403f360] thread_get_buffer() failed
[h264 @ 000001bc1403f360] decode_slice_header error
[h264 @ 000001bc1403f360] no frame!
[000001bc539058a0] direct3d11 vout display error: SetThumbNailClip failed: 0x800706f4

Process finished with exit code 0
</details>

**Comment by chanchancl** [comment]
经测试
1.使用VLC 3，依旧闪退。
2.使用管理员权限打开，依旧闪退
3.使用软解，可以稳定运行

当然，软解是在1.2.都已经应用的情况下开的，
不过我推测主要起作用的还是3

**Comment by chanchancl** [comment]
> 经测试
> 1.使用VLC 3，依旧闪退。
> 2.使用管理员权限打开，依旧闪退
> 3.使用软解，可以稳定运行
> 
> 当然，软解是在1.2.都已经应用的情况下开的，
> 不过我推测主要起作用的还是3

补充。。。运行了将近一个小时后，还是出现了一次闪退，
不过比之前好多了

**Comment by zhimingshenjun** [comment]
如果开软解可以运行 推测可能和显卡硬解或渲染有关 是英伟达7系的显卡吗？有群友反馈7系显卡闪退概率比较高
另外试试更新显卡驱动看看

**Comment by chanchancl** [comment]
显卡是 1660
目前的驱动是 460.79
最新的好像是 461.09， 我尝试更新看看

**Comment by chanchancl** [comment]
新增一个闪退场景。
在删除1.0版本，解压1.1版本之后

首次打开时，可以快速打开，在没有打开直播间的前提下，打开了 投喂作者
闪退

后续再次打开没这个问题，仅出现在首次打开的时候

**Comment by zhimingshenjun** [comment]
试试当前版本还会不会闪退

**Comment by chanchancl** [comment]
v1.1 依然会闪退

**Comment by chanchancl** [comment]
V2.1 VLC3.0 已经不会闪退了，但是偶尔会报这个错误并弹窗

2021-02-13 19:27:30,902 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 767, in stopDanmuMessage
TypeError: 'method' object is not connected
2021-02-13 19:27:31,161 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 882, in setMedia
TypeError: 'method' object is not connected
2021-02-13 19:27:31,163 [Dummy-12    ] [INFO ]  尝试打开 8792912 的弹幕Socket
2021-02-13 19:30:01,082 [Dummy-13    ] [ERROR]  HTTPSConnectionPool(host='api.live.bilibili.com', port=443): Max retries exceeded with url: /room/v2/Room/get_by_ids (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017D19B2CE08>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2021-02-13 19:42:30,468 [Dummy-14    ] [ERROR]  
************!!!UNCAUGHT EXCEPTION!!!*********************
Type: <class 'requests.exceptions.ConnectionError'>
Value: HTTPSConnectionPool(host='i0.hdslb.com', port=443): Max retries exceeded with url: /bfs/live/keyframe02131941000022347054a1qgxq.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017D19A8C448>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Traceback:
  File "LiverSelect.py", line 175, in run
   File "site-packages\requests\api.py", line 76, in get
   File "site-packages\requests\api.py", line 61, in request
   File "site-packages\requests\sessions.py", line 530, in request
   File "site-packages\requests\sessions.py", line 643, in send
   File "site-packages\requests\adapters.py", line 516, in send
************************************************************
