### ISSUE TITLE
【bug】【轻微】短暂断网/网络波动的问题

### ISSUE THREAD

**Issue by SineObama** [zhimingshenjun/DD_Monitor#95]
【环境】2.3版本；win10。
【描述】主动重新连接网络（wifi）时会弹窗提示错误（可以手动刷新直播）。另外碰到一次直接卡死，可能是含有网卡硬件问题的网络波动，我打开百度卡了很久，刚刚断开wifi页面就出来了，但程序卡死了。
【日志】弹窗错误日志文件如下：
```
2021-02-20 23:21:15,900 [MainThread  ] [INFO ]  系统信息: 

主机名:           SINE-ASUS
OS 名称:          Microsoft Windows 10 家庭中文版
OS 版本:          10.0.18363 暂缺 Build 18363
OS 制造商:        Microsoft Corporation
OS 配置:          独立工作站
OS 构建类型:      Multiprocessor Free
注册的所有人:     asus
注册的组织:       Microsoft
产品 ID:          00342-33120-98227-AAOEM
初始安装日期:     2020/3/8, 1:13:48
系统启动时间:     2021/1/31, 10:05:38
系统制造商:       ASUSTeK COMPUTER INC.
系统型号:         X550JX
系统类型:         x64-based PC
处理器:           安装了 1 个处理器。
                  [01]: Intel64 Family 6 Model 60 Stepping 3 GenuineIntel ~2564 Mhz
BIOS 版本:        American Megatrends Inc. X550JX.209, 2015/10/31
Windows 目录:     C:\WINDOWS
系统目录:         C:\WINDOWS\system32
启动设备:         \Device\HarddiskVolume7
系统区域设置:     zh-cn;中文(中国)
输入法区域设置:   en-us;英语(美国) 
时区:             (UTC+08:00) 北京，重庆，香港特别行政区，乌鲁木齐
物理内存总量:     7,633 MB
可用的物理内存:   1,765 MB
虚拟内存: 最大值: 28,449 MB
虚拟内存: 可用:   13,066 MB
虚拟内存: 使用中: 15,383 MB
页面文件位置:     C:\pagefile.sys
域:               WORKGROUP
登录服务器:       \\SINE-ASUS
修补程序:         安装了 19 个修补程序。
                  [01]: KB4586878
                  [02]: KB4497165
                  [03]: KB4517245
                  [04]: KB4535680
                  [05]: KB4537759
                  [06]: KB4538674
                  [07]: KB4541338
                  [08]: KB4552152
                  [09]: KB4560959
                  [10]: KB4561600
                  [11]: KB4565554
                  [12]: KB4569073
                  [13]: KB4576751
                  [14]: KB4577670
                  [15]: KB4580325
                  [16]: KB4584229
                  [17]: KB4586863
                  [18]: KB4598479
                  [19]: KB4598229
网卡:             安装了 4 个 NIC。
                  [01]: Sangfor SSL VPN CS Support System VNIC
                      连接名:      以太网 4
                      状态:        媒体连接已中断
                  [02]: TAP-Windows Adapter V9
                      连接名:      以太网 2
                      状态:        媒体连接已中断
                  [03]: Realtek PCIe GBE Family Controller
                      连接名:      以太网
                      状态:        媒体连接已中断
                  [04]: Broadcom 802.11n Network Adapter
                      连接名:      WLAN
                      启用 DHCP:   是
                      DHCP 服务器: 192.168.0.1
                      IP 地址
                        [01]: 192.168.0.106
                        [02]: fe80::11f6:a6e1:c747:20fd
Hyper-V 要求:     虚拟机监视器模式扩展: 是
                  固件中已启用虚拟化: 是
                  二级地址转换: 是
                  数据执行保护可用: 是

2021-02-20 23:21:15,900 [MainThread  ] [INFO ]  GPU信息: 
AdapterCompatibility=NVIDIA
Caption=NVIDIA GeForce GTX 950M
DeviceID=VideoController1
DriverDate=20171204000000.000000-000
DriverVersion=23.21.13.8857
VideoModeDescription=


AdapterCompatibility=Intel Corporation
Caption=Intel(R) HD Graphics 4600
DeviceID=VideoController2
DriverDate=20161110000000.000000-000
DriverVersion=20.19.15.4549
VideoModeDescription=1920 x 1080 x 4294967296 种颜色
2021-02-20 23:21:15,901 [MainThread  ] [INFO ]  libvlc env: PYTHON_VLC_LIB_PATH=
2021-02-20 23:21:15,901 [MainThread  ] [INFO ]  plugin env: PYTHON_VLC_MODULE_PATH=
2021-02-20 23:21:15,901 [MainThread  ] [INFO ]  libvlc path: D:\Program Files\DD监控室v2.3 (VLC3.0内核)\libvlc.dll
2021-02-20 23:21:15,901 [MainThread  ] [INFO ]  vlc version: b'3.0.12 Vetinari'
2021-02-20 23:21:30,635 [MainThread  ] [INFO ]  嵌入窗0 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-20 23:21:30,734 [MainThread  ] [INFO ]  悬浮窗9 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-20 23:21:30,765 [MainThread  ] [INFO ]  VLC设置完毕 1 / 9
2021-02-20 23:21:30,855 [MainThread  ] [INFO ]  嵌入窗1 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-20 23:21:30,945 [MainThread  ] [INFO ]  悬浮窗10 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-20 23:21:30,958 [MainThread  ] [INFO ]  VLC设置完毕 2 / 9
2021-02-20 23:21:31,050 [MainThread  ] [INFO ]  嵌入窗2 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-20 23:21:31,143 [MainThread  ] [INFO ]  悬浮窗11 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-20 23:21:31,152 [MainThread  ] [INFO ]  VLC设置完毕 3 / 9
2021-02-20 23:21:31,236 [MainThread  ] [INFO ]  嵌入窗3 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-20 23:21:31,335 [MainThread  ] [INFO ]  悬浮窗12 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-20 23:21:31,344 [MainThread  ] [INFO ]  VLC设置完毕 4 / 9
2021-02-20 23:21:31,431 [MainThread  ] [INFO ]  嵌入窗4 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-20 23:21:31,511 [MainThread  ] [INFO ]  悬浮窗13 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-20 23:21:31,518 [MainThread  ] [INFO ]  VLC设置完毕 5 / 9
2021-02-20 23:21:31,599 [MainThread  ] [INFO ]  嵌入窗5 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-20 23:21:31,685 [MainThread  ] [INFO ]  悬浮窗14 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-20 23:21:31,695 [MainThread  ] [INFO ]  VLC设置完毕 6 / 9
2021-02-20 23:21:31,780 [MainThread  ] [INFO ]  嵌入窗6 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-20 23:21:31,867 [MainThread  ] [INFO ]  悬浮窗15 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-20 23:21:31,875 [MainThread  ] [INFO ]  VLC设置完毕 7 / 9
2021-02-20 23:21:31,968 [MainThread  ] [INFO ]  嵌入窗7 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-20 23:21:32,069 [MainThread  ] [INFO ]  悬浮窗16 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-20 23:21:32,082 [MainThread  ] [INFO ]  VLC设置完毕 8 / 9
2021-02-20 23:21:32,176 [MainThread  ] [INFO ]  嵌入窗8 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-20 23:21:32,284 [MainThread  ] [INFO ]  悬浮窗17 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-20 23:21:32,296 [MainThread  ] [INFO ]  VLC设置完毕 9 / 9
2021-02-20 23:21:32,651 [MainThread  ] [INFO ]  UI构造完毕
2021-02-20 23:21:35,089 [Dummy-1     ] [INFO ]  弹幕IP: 120.92.144.250
2021-02-20 23:21:35,873 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 867, in setMedia
TypeError: 'method' object is not connected
2021-02-20 23:21:35,878 [Dummy-2     ] [INFO ]  尝试打开 33989 的弹幕Socket
2021-02-20 23:21:35,990 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 867, in setMedia
TypeError: 'method' object is not connected
2021-02-20 23:21:36,074 [Dummy-3     ] [INFO ]  尝试打开 876396 的弹幕Socket
2021-02-20 23:21:36,493 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 867, in setMedia
TypeError: 'method' object is not connected
2021-02-20 23:21:36,508 [Dummy-4     ] [INFO ]  尝试打开 41682 的弹幕Socket
2021-02-20 23:21:36,689 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 867, in setMedia
TypeError: 'method' object is not connected
2021-02-20 23:21:36,696 [Dummy-5     ] [INFO ]  尝试打开 3597056 的弹幕Socket
2021-02-20 23:21:46,833 [MainThread  ] [INFO ]  exchange:1:876396
2021-02-20 23:21:46,833 [MainThread  ] [INFO ]  
2021-02-20 23:21:46,833 [MainThread  ] [INFO ]  1
2021-02-20 23:21:46,834 [MainThread  ] [INFO ]   
2021-02-20 23:21:46,834 [MainThread  ] [INFO ]  1
2021-02-20 23:21:46,834 [MainThread  ] [INFO ]  
2021-02-20 23:23:02,420 [MainThread  ] [ERROR]  
************!!!UNCAUGHT EXCEPTION!!!*********************
Type: <class 'requests.exceptions.ConnectionError'>
Value: HTTPSConnectionPool(host='api.live.bilibili.com', port=443): Max retries exceeded with url: /xlive/web-room/v1/index/getInfoByRoom?room_id=3597056 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002699A8BAFC8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Traceback:
  File "VideoWidget_vlc.py", line 832, in mediaReload
   File "VideoWidget_vlc.py", line 941, in setTitle
   File "site-packages\requests\api.py", line 76, in get
   File "site-packages\requests\api.py", line 61, in request
   File "site-packages\requests\sessions.py", line 530, in request
   File "site-packages\requests\sessions.py", line 643, in send
   File "site-packages\requests\adapters.py", line 516, in send
************************************************************

2021-02-20 23:25:39,776 [Dummy-6     ] [INFO ]  尝试打开 33989 的弹幕Socket

```

**Comment by zhimingshenjun** [comment]
断网会导致监控室卡死 暂时没有精力修
