### ISSUE TITLE
【bug】

### ISSUE THREAD

**Issue by yiwcs** [zhimingshenjun/DD_Monitor#98]
描述：2.1正式版，win10，打开后观看5分钟左右就会弹出错误报告，原因不明。
 `2021-02-21 21:00:09,457 [MainThread  ] [INFO ]  系统信息: 

主机名:           DESKTOP-KIRITO
OS 名称:          Microsoft Windows 10 专业版
OS 版本:          10.0.18363 暂缺 Build 18363
OS 制造商:        Microsoft Corporation
OS 配置:          独立工作站
OS 构建类型:      Multiprocessor Free
注册的所有人:     kirito
注册的组织:       
产品 ID:          00330-80000-00000-AA558
初始安装日期:     2020/6/26, 22:19:25
系统启动时间:     2021/2/21, 19:52:58
系统制造商:       System manufacturer
系统型号:         System Product Name
系统类型:         x64-based PC
处理器:           安装了 1 个处理器。
                  [01]: Intel64 Family 6 Model 158 Stepping 13 GenuineIntel ~3600 Mhz
BIOS 版本:        American Megatrends Inc. 1602, 2020/6/4
Windows 目录:     C:\Windows
系统目录:         C:\Windows\system32
启动设备:         \Device\HarddiskVolume5
系统区域设置:     zh-cn;中文(中国)
输入法区域设置:   zh-cn;中文(中国)
时区:             (UTC+08:00) 北京，重庆，香港特别行政区，乌鲁木齐
物理内存总量:     16,301 MB
可用的物理内存:   12,029 MB
虚拟内存: 最大值: 19,245 MB
虚拟内存: 可用:   11,066 MB
虚拟内存: 使用中: 8,179 MB
页面文件位置:     C:\pagefile.sys
域:               WORKGROUP
登录服务器:       \\DESKTOP-KIRITO
修补程序:         安装了 17 个修补程序。
                  [01]: KB4601056
                  [02]: KB4513661
                  [03]: KB4516115
                  [04]: KB4517245
                  [05]: KB4528759
                  [06]: KB4535680
                  [07]: KB4560959
                  [08]: KB4561600
                  [09]: KB4569073
                  [10]: KB4576751
                  [11]: KB4576754
                  [12]: KB4577670
                  [13]: KB4580325
                  [14]: KB4586863
                  [15]: KB4598479
                  [16]: KB4601395
                  [17]: KB5001028
网卡:             安装了 2 个 NIC。
                  [01]: Intel(R) Wireless-AC 9560 160MHz
                      连接名:      WLAN
                      状态:        媒体连接已中断
                  [02]: Intel(R) Ethernet Connection (7) I219-V
                      连接名:      以太网
                      启用 DHCP:   是
                      DHCP 服务器: 192.168.31.1
                      IP 地址
                        [01]: 192.168.31.148
Hyper-V 要求:     虚拟机监视器模式扩展: 是
                  固件中已启用虚拟化: 是
                  二级地址转换: 是
                  数据执行保护可用: 是

2021-02-21 21:00:09,457 [MainThread  ] [INFO ]  GPU信息: 
AdapterCompatibility=NVIDIA
Caption=NVIDIA GeForce GTX 1070 Ti
DeviceID=VideoController1
DriverDate=20210122000000.000000-000
DriverVersion=27.21.14.6140
VideoModeDescription=2560 x 1440 x 4294967296 种颜色
2021-02-21 21:00:09,458 [MainThread  ] [INFO ]  libvlc env: PYTHON_VLC_LIB_PATH=
2021-02-21 21:00:09,458 [MainThread  ] [INFO ]  plugin env: PYTHON_VLC_MODULE_PATH=
2021-02-21 21:00:09,458 [MainThread  ] [INFO ]  libvlc path: D:\DD监控室v2.1\libvlc.dll
2021-02-21 21:00:09,458 [MainThread  ] [INFO ]  vlc version: b'2.2.8 Weatherwax'
2021-02-21 21:00:09,987 [MainThread  ] [INFO ]  嵌入窗0 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-21 21:00:10,006 [MainThread  ] [INFO ]  悬浮窗9 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-21 21:00:10,015 [MainThread  ] [INFO ]  VLC设置完毕 1 / 9
2021-02-21 21:00:10,029 [MainThread  ] [INFO ]  嵌入窗1 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-21 21:00:10,046 [MainThread  ] [INFO ]  悬浮窗10 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-21 21:00:10,049 [MainThread  ] [INFO ]  VLC设置完毕 2 / 9
2021-02-21 21:00:10,063 [MainThread  ] [INFO ]  嵌入窗2 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-21 21:00:10,079 [MainThread  ] [INFO ]  悬浮窗11 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-21 21:00:10,082 [MainThread  ] [INFO ]  VLC设置完毕 3 / 9
2021-02-21 21:00:10,096 [MainThread  ] [INFO ]  嵌入窗3 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-21 21:00:10,112 [MainThread  ] [INFO ]  悬浮窗12 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-21 21:00:10,115 [MainThread  ] [INFO ]  VLC设置完毕 4 / 9
2021-02-21 21:00:10,128 [MainThread  ] [INFO ]  嵌入窗4 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-21 21:00:10,143 [MainThread  ] [INFO ]  悬浮窗13 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-21 21:00:10,146 [MainThread  ] [INFO ]  VLC设置完毕 5 / 9
2021-02-21 21:00:10,161 [MainThread  ] [INFO ]  嵌入窗5 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-21 21:00:10,176 [MainThread  ] [INFO ]  悬浮窗14 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-21 21:00:10,179 [MainThread  ] [INFO ]  VLC设置完毕 6 / 9
2021-02-21 21:00:10,194 [MainThread  ] [INFO ]  嵌入窗6 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-21 21:00:10,209 [MainThread  ] [INFO ]  悬浮窗15 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-21 21:00:10,213 [MainThread  ] [INFO ]  VLC设置完毕 7 / 9
2021-02-21 21:00:10,227 [MainThread  ] [INFO ]  嵌入窗7 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-21 21:00:10,242 [MainThread  ] [INFO ]  悬浮窗16 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-21 21:00:10,246 [MainThread  ] [INFO ]  VLC设置完毕 8 / 9
2021-02-21 21:00:10,260 [MainThread  ] [INFO ]  嵌入窗8 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: False, 启用弹幕?: True
2021-02-21 21:00:10,275 [MainThread  ] [INFO ]  悬浮窗17 VLC 播放器构造完毕, 缓存大小: 2048000kb, 缓存路径: , 置顶?: True, 启用弹幕?: True
2021-02-21 21:00:10,278 [MainThread  ] [INFO ]  VLC设置完毕 9 / 9
2021-02-21 21:00:10,390 [MainThread  ] [INFO ]  UI构造完毕
2021-02-21 21:00:10,414 [Dummy-1     ] [INFO ]  弹幕IP: 120.92.78.57
2021-02-21 21:00:10,568 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 866, in mediaStop
TypeError: 'method' object is not connected
2021-02-21 21:00:10,617 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 866, in mediaStop
TypeError: 'method' object is not connected
2021-02-21 21:00:10,654 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 866, in mediaStop
TypeError: 'method' object is not connected
2021-02-21 21:00:11,051 [MainThread  ] [ERROR]  停止弹幕出错
Traceback (most recent call last):
  File "VideoWidget_vlc.py", line 882, in setMedia
TypeError: 'method' object is not connected
2021-02-21 21:00:11,055 [Dummy-2     ] [INFO ]  尝试打开 21547895 的弹幕Socket
`

**Comment by yiwcs** [comment]
找到了2.3版本，我先试下
